# Generated by Django 4.0.1 on 2022-04-06 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing_books',
            name='book_seller',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.user_details', verbose_name='book_seller_id'),
        ),
    ]
