# Generated by Django 4.0.1 on 2022-04-29 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_book_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing_books',
            name='buyer_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_id_listing_books', to='backend.user_details', verbose_name='buyer_id'),
        ),
    ]
