# Generated by Django 4.0.1 on 2022-04-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_listing_books_buyer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='address_pincode',
            field=models.BigIntegerField(default=None),
        ),
        migrations.DeleteModel(
            name='file_upload',
        ),
    ]
