# Generated by Django 4.0.1 on 2022-05-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_user_details_address_line_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_details',
            old_name='city',
            new_name='block',
        ),
        migrations.AddField(
            model_name='user_details',
            name='district',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
